# Generated by Django 2.2.7 on 2019-12-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
